fix(mrs_and_mmdb.yml): new one

diff --git a/.github/workflows/mrs_and_mmdb.yml b/.github/workflows/mrs_and_mmdb.yml
--- a/.github/workflows/mrs_and_mmdb.yml
+++ b/.github/workflows/mrs_and_mmdb.yml
@@ -91,7 +91,8 @@ jobs:
       env:
         NO_SKIP: true
       run: |
-        cd community || exit 1
+        cd community || { echo "Failed to enter community directory"; exit 1; }
+        go mod tidy
         mkdir -p data
         curl -sSL https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/accelerated-domains.china.conf | grep "server=" | grep -v "#" | sed 's/ *server=\/\([^\/]*\)\/.*/\1/g' > ./data/cn
         go run ./ --datapath=./data --outputname geosite.dat
@@ -101,7 +102,7 @@ jobs:
 
     - name: Remove untracked files
       run: |
-        git clean -f china.txt china6.txt CN-ip-cidr.txt mihomo.deb
+        rm   china.txt china6.txt CN-ip-cidr.txt mihomo.deb
 
     - name: Commit and push mrs
       env:
@@ -111,5 +112,10 @@ jobs:
         git config --local user.email "101653181+github-actions[bot]@users.noreply.github.com"
         git add all_cn.txt all_cn_ipv6.txt CN-ip-cidr.mrs Country.mmdb geosite.dat geosite.list
         commit_message="Update mrs and mmdb and Geosite Data on $(date +'%Y-%m-%d')"
-        git commit -m "$commit_message" || true
-        git push -f -u origin main
+        # 检查是否有需要提交的变更
+        if [[ -n "$(git status --porcelain)" ]]; then
+          git commit -m "$commit_message"
+          git push -u origin main
+        else
+          echo "No changes to commit."
+        fi
